version: '3.8'

services:
  database:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: healthmeal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./docker/postgresql/product/:/docker-entrypoint-initdb.d
