name: Orders Integrator CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'libraries/orders-integrator/**'

jobs:
  build:
    name: Build Orders Integrator library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Orders Integrator library
        run: mvn clean package --batch-mode --also-make --projects :orders-integrator
