name: Orders CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'services/orders/**'

jobs:
  build:
    name: Build Products application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Orders application
        run: mvn clean package --batch-mode --also-make --projects :orders
